site_name: kcp Documentation
repo_url: https://github.com/kcp-dev/kcp
site_url: https://ncdc.github.io/kcp/

docs_dir: '../../content/en'
site_dir: '../../generated/en'

theme:
  name: material
  language: en
  custom_dir: '../../overrides/'
  features:
  #- navigation.tabs
  #- navigation.tabs.sticky
  - navigation.indexes
  - content.code.copy
  - content.code.annotate
  logo: logo.png
  favicon: favicons/favicon.ico

#nav:
#- Concepts: concepts/
#- Reference: 'https://TODO.com'
#- Blog: 'https://kcp.io/blog'
#- Contribute: 'https://github.com/kcp-dev/kcp/blob/main/CONTRIBUTING.md'

extra:
  version:
    provider: mike
  alternate:
  - name: English
    link: /en/
    lang: en

plugins:
  - awesome-pages
  - search
  - macros

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- admonition

extra_css:
- stylesheets/crd.css

watch:
- mkdocs.yml
- ../../content/en
- ../../overrides
