apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v220909-10032c35.workspaces.tenancy.kcp.dev
  - v220909-c255fd13.clusterworkspaces.tenancy.kcp.dev
  - v220912-84445eab.clusterworkspacetypes.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
