apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homebucket
spec:
  defaultAPIBindings:
  - path: root
    name: tenancy.kcp.dev
  defaultChildWorkspaceType:
    name: home
    path: root
  limitAllowedChildren:
    types:
    - name: homebucket
      path: root
    - name: home
      path: root
  limitAllowedParents:
    types:
    - name: homebucket
      path: root
    - name: homeroot
      path: root
