apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homeroot
spec:
  defaultAPIBindings:
  - path: root
    name: tenancy.kcp.dev
  defaultChildWorkspaceType:
    name: homebucket
    path: root
  limitAllowedChildren:
    types:
    - name: homebucket
      path: root
  limitAllowedParents:
    types:
    - name: root
      path: root
