name: Andy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "release-*"

concurrency:
  group: ${{ github.workflow }}

jobs:
  andy:
    name: andy
    runs-on: ubuntu-latest
    steps:
      - run: env|sort
